[package]
name = "nixpkgs-check-by-name"
version = "0.1.1"
edition = "2021"

[dependencies]
rnix = "0.11.0"
regex = "1.10.5"
clap = { version = "4.5.9", features = ["derive"] }
serde_json = "1.0.120"
tempfile = "3.10.1"
serde = { version = "1.0.204", features = ["derive"] }
anyhow = "1.0"
lazy_static = "1.5.0"
colored = "2.1.0"
itertools = "0.13.0"
rowan = "0.15.15"
indoc = "2.0.5"
relative-path = "1.9.3"
textwrap = "0.16.1"

[dev-dependencies]
temp-env = "0.3.6"
