[package]
name = "nixpkgs-vet"
version = "0.1.4"
edition = "2021"

[dependencies]
rnix = "0.11.0"
regex = "1.11.0"
clap = { version = "4.5.20", features = ["derive"] }
serde_json = "1.0.132"
tempfile = "3.13.0"
serde = { version = "1.0.213", features = ["derive"] }
anyhow = "1.0"
lazy_static = "1.5.0"
colored = "2.1.0"
itertools = "0.13.0"
rowan = "0.15.16"
indoc = "2.0.5"
relative-path = "1.9.3"
textwrap = "0.16.1"
derive-enum-from-into = "0.2.0"
derive-new = "0.7.0"
derive_more = { version = "1.0.0", features = ["display"] }

[dev-dependencies]
pretty_assertions = "1.4.1"
temp-env = "0.3.6"
